// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "description": "用于负载均衡与监控系统检测 Go 服务是否存活。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.healthResponse"
                        }
                    }
                }
            }
        },
        "/internal/sync": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "文档存在且公开时写入索引；不存在、下架或菜单不可见时删除索引。仅限 Strapi 内网调用。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "内部同步"
                ],
                "summary": "同步单篇文档索引",
                "parameters": [
                    {
                        "description": "需要同步的文档标识",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.syncRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.syncResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/main.errorResponse"
                        }
                    }
                }
            }
        },
        "/search": {
            "get": {
                "description": "在标题和正文中搜索已发布且具有已发布菜单路径的文档。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "搜索"
                ],
                "summary": "搜索公开文档",
                "parameters": [
                    {
                        "type": "string",
                        "description": "搜索关键词",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码，默认 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量，默认 20，最大 100",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.searchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/main.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.errorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "search is temporarily unavailable"
                }
            }
        },
        "main.formattedSearchHit": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": "...使用 \u003cmark\u003e快速\u003c/mark\u003e开始完成配置..."
                },
                "title": {
                    "type": "string",
                    "example": "\u003cmark\u003e快速\u003c/mark\u003e开始"
                }
            }
        },
        "main.healthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "main.searchHit": {
            "type": "object",
            "properties": {
                "_formatted": {
                    "$ref": "#/definitions/main.formattedSearchHit"
                },
                "content": {
                    "type": "string",
                    "example": "完成产品配置的入门文档。"
                },
                "id": {
                    "type": "string",
                    "example": "quick-start"
                },
                "title": {
                    "type": "string",
                    "example": "快速开始"
                },
                "url": {
                    "type": "string",
                    "example": "/quick-start"
                }
            }
        },
        "main.searchResponse": {
            "type": "object",
            "properties": {
                "hits": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.searchHit"
                    }
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "pageSize": {
                    "type": "integer",
                    "example": 20
                },
                "totalHits": {
                    "type": "integer",
                    "example": 1
                },
                "totalPages": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "main.syncRequest": {
            "type": "object",
            "properties": {
                "docId": {
                    "type": "string"
                }
            }
        },
        "main.syncResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "synced"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "内部同步接口使用 Bearer Token 鉴权。",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "文档中心搜索服务 API",
	Description:      "面向公开已发布文档的全文搜索与索引同步服务。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
